name = 'Minimal-theme'
license = 'MIT'
licenselink = 'https://github.com/mrckarlsson/minimal-theme/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mrckalrsson/minimal-theme'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Christian Karlsson'
  homepage = 'https://wwwkarlsson.xyz/'


